using System.CodeDom.Compiler;

namespace Appegy.Union.Generator;

public class HeaderPart<T> : GeneratorPart<T> where T : struct
{
    public override void Generate(IndentedTextWriter codeWriter, T input)
    {
        codeWriter.WriteLine("// <auto-generated/>");
    }
}