name: Build Sample Application

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Appegy.Union.Generator~/Appegy.Union.Generator.slnx

      - name: Build solution
        run: dotnet build Appegy.Union.Generator~/Appegy.Union.Generator.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Appegy.Union.Generator~/Appegy.Union.Generator.Tests/Appegy.Union.Generator.Tests.csproj --configuration Release --no-build --verbosity normal
